/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mwbs;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import jdk.nashorn.internal.ir.Statement;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author Imperator
 */
public class FrAdminAddMovie extends javax.swing.JFrame {

    /**
     * Creates new form FrAdminMangeMovies
     */
    Connection conMain;
    Statement stmtMain;
    PreparedStatement pstmtMain;
    ResultSet rsMain;
    File flImage = null;
    public FrAdminAddMovie() {
        labelBackground();
        initComponents();
        tfldID.setText(String.valueOf(incrementID()));
    }
    
    private void labelBackground(){
        try {
            BufferedImage bfimgBackground = ImageIO.read(new File("src/mwbs/images/background.png"));
            Image imgBackground = bfimgBackground.getScaledInstance(247, 246, java.awt.Image.SCALE_SMOOTH);
            setContentPane(new JLabel(new ImageIcon(imgBackground)));
        }
        catch (IOException ex) {
        }
    }
    
    class imageFilter extends javax.swing.filechooser.FileFilter{
        @Override
        public boolean accept(File flFile){
            return flFile.isDirectory() || flFile.getAbsolutePath().endsWith(".jpg");
        }
        @Override
        public String getDescription(){
            return "Image File (*.jpg)";
        }
    }
    
    private void connectDatabase(){
        try{
            String strURL = "jdbc:ucanaccess://MWBS.accdb";
            String strDatabaseUsername = "";
            String strDatabasePassword = "";
            conMain = DriverManager.getConnection(strURL, strDatabaseUsername, strDatabasePassword);
        }   
        catch(SQLException error){
        }
    }
    
    private int incrementID(){
        connectDatabase();
        String strID;
        int intID = 0;
        String strQuery = "SELECT "
                + "movie_ID "
                + "from MovieList "
                + "order by movie_ID";
        try{
            pstmtMain = conMain.prepareStatement(strQuery);
            rsMain = pstmtMain.executeQuery();
            while(rsMain.next()){
                strID = rsMain.getString("movie_ID");
                intID = Integer.parseInt(strID)+1;
            }
        }
        catch(SQLException error){
            System.out.println(error);
        }
        if(intID == 0){
            return 1000;
        }
        else{
            return intID;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flchoFileChooser = new javax.swing.JFileChooser();
        lblID = new javax.swing.JLabel();
        tfldID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        tfldName = new javax.swing.JTextField();
        lblTickets = new javax.swing.JLabel();
        tfldTickets = new javax.swing.JTextField();
        btnFileChooser = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        flchoFileChooser.setFileFilter(new imageFilter());
        flchoFileChooser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID");

        tfldID.setEnabled(false);

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");

        lblTickets.setForeground(new java.awt.Color(255, 255, 255));
        lblTickets.setText("Tickets");

        btnFileChooser.setBackground(new java.awt.Color(230, 175, 82));
        btnFileChooser.setForeground(new java.awt.Color(255, 255, 255));
        btnFileChooser.setText("Choose Picture");
        btnFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileChooserActionPerformed(evt);
            }
        });

        lblImage.setBackground(new java.awt.Color(230, 175, 82));
        lblImage.setMaximumSize(new java.awt.Dimension(120, 180));
        lblImage.setMinimumSize(new java.awt.Dimension(120, 180));
        lblImage.setOpaque(true);
        lblImage.setPreferredSize(new java.awt.Dimension(120, 180));

        btnSubmit.setBackground(new java.awt.Color(230, 175, 82));
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(230, 175, 82));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfldID)
                    .addComponent(lblTickets, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(tfldTickets)
                    .addComponent(tfldName)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID)
                            .addComponent(lblName))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTickets)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfldTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(btnFileChooser))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileChooserActionPerformed
        int intOption = flchoFileChooser.showOpenDialog(this);
        if(intOption == JFileChooser.APPROVE_OPTION){
            flImage = flchoFileChooser.getSelectedFile();
            try{
                BufferedImage bfimgFile = ImageIO.read(new File(flImage.getAbsolutePath()));
                Image imgFile = bfimgFile.getScaledInstance(120, 180, java.awt.Image.SCALE_SMOOTH);
                lblImage.setIcon(new ImageIcon(imgFile));
            }
            catch(IOException error){
                System.out.println(error);
            }
        }
    }//GEN-LAST:event_btnFileChooserActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        connectDatabase();
        String strID = tfldID.getText();
        String strName = tfldName.getText();
        String strTickets = tfldTickets.getText();
        String strQuery = "INSERT INTO "
                + "MovieList(movie_ID, movie_Name, movie_Tickets, movie_Reserved, movie_Showing)"
                + " VALUES("+strID+",'"+strName+"','"+strTickets+"','"+"0"+"','"+"N"+"')";
        if (tfldName.equals("")||tfldTickets.equals("")||flImage == null) {
            java.awt.Toolkit.getDefaultToolkit().beep();
        }
        else {
            try {
                pstmtMain = conMain.prepareStatement(strQuery);
                pstmtMain.execute();
                File flDestination = new File("src\\mwbs\\images\\movies\\"+tfldID.getText()+".jpg");
                FileUtils.copyFile(flImage, flDestination);
                new FrAdminManageMovie().setVisible(true);
                this.dispose();
            }
            catch (SQLException | IOException error) {
                System.out.println(error);
                java.awt.Toolkit.getDefaultToolkit().beep();
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        new FrAdminManageMovie().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAdminAddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAdminAddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAdminAddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAdminAddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrAdminAddMovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFileChooser;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JFileChooser flchoFileChooser;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTickets;
    private javax.swing.JTextField tfldID;
    private javax.swing.JTextField tfldName;
    private javax.swing.JTextField tfldTickets;
    // End of variables declaration//GEN-END:variables
}
