/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mwbs;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import jdk.nashorn.internal.ir.Statement;

/**
 *
 * @author Imperator
 */
public class FrReserveManage extends javax.swing.JFrame {

    /**
     * Creates new form FrReserveTicket
     */
    Connection conMain;
    Statement stmtMain;
    PreparedStatement pstmtMain;
    ResultSet rsMain;
    int intTicketID;
    int intMovieID;
    public FrReserveManage(int intID) {
        this.intTicketID  = intID;
        labelBackground();
        initComponents();
        getMovie();
    }
    
    private FrReserveManage(){
        this.intTicketID = 1000;
        initComponents();
        getMovie();
    }
    
    private void labelBackground(){
        try {
            BufferedImage bfimgBackground = ImageIO.read(new File("src/mwbs/images/background.png"));
            Image imgBackground = bfimgBackground.getScaledInstance(427, 405, java.awt.Image.SCALE_SMOOTH);
            setContentPane(new JLabel(new ImageIcon(imgBackground)));
        }
        catch (IOException ex) {
        }
    }
    
    private void connectDatabase(){
        try{
            String strURL = "jdbc:ucanaccess://MWBS.accdb";
            String strDatabaseUsername = "";
            String strDatabasePassword = "";
            conMain = DriverManager.getConnection(strURL, strDatabaseUsername, strDatabasePassword);
        }   
        catch(SQLException error){
        }
    }
    
    private void getMovie(){
        connectDatabase();
        File flImage = null;
        DateFormat dtfrDefaultFormat = new SimpleDateFormat("MM/dd/yyyy");
        String strQuery = "SELECT"
                + " TicketList.ticket_ID, TicketList.ticket_Code, TicketList.ticket_Name, TicketList.ticket_Movie, TicketList.ticket_Date, TicketList.ticket_Status"
                + " MovieList.movie_ID, MovieList.movie_Name"
                + " FROM TicketList, MovieList"
                + " WHERE TicketList.ticket_Movie=MovieList.movie_ID";
        try{
            pstmtMain = conMain.prepareStatement(strQuery);
            rsMain = pstmtMain.executeQuery();
            while(rsMain.next()){
                if(rsMain.getString("ticket_ID").equals(String.valueOf(intTicketID))){
                    lblCode.setText(rsMain.getString("ticket_Code"));
                    lblName.setText(rsMain.getString("ticket_Name"));
                    this.intMovieID = rsMain.getInt("ticket_Movie");
                    lblDate.setText(dtfrDefaultFormat.format(rsMain.getDate("ticket_Date")));
                    String strStatus = rsMain.getString("ticket_Status");
                    if(strStatus.equals("R")){
                        lblStatus.setText("RESERVED");
                    }
                    else if(strStatus.equals("C")){
                        lblStatus.setText("CANCELLED");
                        btnCancelReservation.setEnabled(false);
                    }
                    lblMovieTitle.setText(rsMain.getString("movie_Name"));
                    flImage = new File("src\\mwbs\\images\\movies\\"+intMovieID+".jpg");
                    try{
                        BufferedImage bfimgFile = ImageIO.read(flImage);
                        Image imgFile = bfimgFile.getScaledInstance(240, 360, java.awt.Image.SCALE_SMOOTH);
                        lblMovieImage.setIcon(new ImageIcon(imgFile));
                    }
                    catch(IOException error){
                        System.out.println(error);
                    }
                }
            }
        }
        catch(SQLException error){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMovieTitle = new javax.swing.JLabel();
        lblMovieImage = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        btnCancelReservation = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblCode = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        lblMovieTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMovieTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovieTitle.setText("jLabel1");

        lblMovieImage.setBackground(new java.awt.Color(255, 153, 51));
        lblMovieImage.setMaximumSize(new java.awt.Dimension(240, 360));
        lblMovieImage.setMinimumSize(new java.awt.Dimension(240, 360));
        lblMovieImage.setOpaque(true);
        lblMovieImage.setPreferredSize(new java.awt.Dimension(240, 360));

        btnReturn.setBackground(new java.awt.Color(230, 175, 82));
        btnReturn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        btnCancelReservation.setBackground(new java.awt.Color(230, 175, 82));
        btnCancelReservation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelReservation.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelReservation.setText("Cancel Reservation");
        btnCancelReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelReservationActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("jLabel1");

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("jLabel2");

        lblCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCode.setForeground(new java.awt.Color(255, 255, 255));
        lblCode.setText("jLabel1");

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblMovieTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMovieImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelReservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblDate)
                            .addComponent(lblCode)
                            .addComponent(lblStatus))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMovieTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(18, 18, 18)
                        .addComponent(lblDate)
                        .addGap(18, 18, 18)
                        .addComponent(lblCode)
                        .addGap(18, 18, 18)
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelReservation)
                        .addGap(18, 18, 18)
                        .addComponent(btnReturn))
                    .addComponent(lblMovieImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        new FrMainTicket().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnCancelReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelReservationActionPerformed
        connectDatabase();
        int intReserved = 0;
        String strReservedQuery = "SELECT "
                    + "movie_ID, movie_Reserved "
                    + "FROM MovieList "
                    + "ORDER BY movie_ID";
        String strTicketQuery = "UPDATE TicketList SET "
                    + "ticket_Status = '"+"C"+"' "
                    + "WHERE ticket_ID = "+intTicketID;
        try{
            pstmtMain = conMain.prepareStatement(strReservedQuery);
            rsMain = pstmtMain.executeQuery();
            while(rsMain.next()){
                if(rsMain.getString("movie_ID").equals(String.valueOf(intMovieID))){
                    intReserved = rsMain.getInt("movie_Reserved");
                }
            }
            String strMovieQuery = "UPDATE MovieList SET "
                        + "movie_Reserved = '"+(intReserved-1)+"' "
                        + "WHERE movie_ID = "+intMovieID;
            pstmtMain = conMain.prepareStatement(strMovieQuery);
            pstmtMain.execute();
            pstmtMain = conMain.prepareStatement(strTicketQuery);
            pstmtMain.execute();
            getMovie();
        }
        catch(SQLException error){
        }
    }//GEN-LAST:event_btnCancelReservationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrReserveManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrReserveManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrReserveManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrReserveManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrReserveManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelReservation;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblMovieImage;
    private javax.swing.JLabel lblMovieTitle;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
